### ISSUE TITLE
Compatibility with Ubuntu MATE 16.04.2 LTS for RPI

### ISSUE THREAD

**Issue by wstevens0n** [rricharz/pi-top-battery-status#11]
Not much of an issue, but I got this working with my Ubuntu Pi-Top project after purging and re-installing wiringPi via git.drogon.net/wiringPi

After that I did a manual install to /home/pi/bin and created a .desktop file under /.config/autostart.

Thanks again for sharing this!

**Comment by rricharz** [comment]
Nice. If you are going to write this up in more detail for Ubuntu users, I am happy to include a link in this repository.

**Comment by wstevens0n** [comment]
Sounds good!

It's in the works. 
https://github.com/wstevens0n/RPI-UbuntuMATE-Pi-Top

I will be sure to give proper credit as well.
