### ISSUE TITLE
Where is the battery?

### ISSUE THREAD

**Issue by crertel** [rricharz/pi-top-battery-status#7]
I've looked at several manuals and pictures of the pi-top, but I can't seem to figure out where the battery is.

Where's the battery, physically?

Thanks!

**Comment by rricharz** [comment]
The pi-topCEED has no battery. In the pi-top laptop, the battery pack is below the keyboard, well protected under a metal plate. It includes 4 battery cells and the intelligent controller.

**Comment by crertel** [comment]
Oh cool! Thank you! :)
