### ISSUE TITLE
Issues with gtk_battery after Update : Hardware not matching expected BCM

### ISSUE THREAD

**Issue by rfv-370** [rricharz/pi-top-battery-status#9]
Hi Rich,
I am getting:
$ gtk_battery
Unable to determine hardware version. I see: Hardware   : BCM2835
,
 - expecting BCM2708 or BCM2709.
If this is a genuine Raspberry Pi then please report this
to projects@drogon.net. If this is not a Raspberry Pi then you
are on your own as wiringPi is designed to support the
Raspberry Pi ONLY.

I can confirm that this a genuine Rpi3 (I think) - is there a way to force gtk_battery to start anyway ?

Best,
Robert

**Comment by rricharz** [comment]
Hi Robert,

I have no idea what's causing this problem. Wiringpi is used in gtk-battery. Can you please check your version number of wiringpi with
`sudo apt-cache policy wiringpi`

The latest version on Raspbian is 2.32. If you have an earlier version, do a 
`sudo apt-get install wiringpi`

Please let me know the outcome. If you have a genuine Raspberry Pi, you might write to projects@drogon.net and report the outcome here.

Best Regards, Rene

**Comment by rricharz** [comment]
Any news on this issue? I am not aware of anybody else observing it.

Best regards, Rene

**Comment by rfv-370** [comment]
Thank you. I update/upgraded, reinstalled and then all came back up normal.BestRobert


      De : Rene Richarz <notifications@github.com>
 À : rricharz/pi-top-battery-status <pi-top-battery-status@noreply.github.com> 
Cc : rfv-370 <robert.vergnes@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Samedi 4 mars 2017 13h08
 Objet : Re: [rricharz/pi-top-battery-status] Issues with gtk_battery after Update : Hardware not matching expected BCM (#9)
   
Any news on this issue? I am not aware of anybody else observing it.Best regards, Rene—
